# Numpy 

# Creating an Array with list, linspace, ones, zeros & other methods
# Functions that can be used with array such as reshape, max, min, randint etc.

In [1]:
import numpy as np
import pandas as pd

In [5]:
# Numpy Arrays

my_list = [1,2,3]

In [6]:
# creating numpy array
# casting that list as an array

arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)
         # three dimensional array
         # three rows and three columns
        #list of list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# creating array
#similar to python range function from for loop
np.arange(0,10) # 0 - 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2) # adding step size from 0 to 10 with a step of 2

array([ 0,  2,  4,  6,  8, 10])

In [17]:
# array with zeros

np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5)) # first number = row, 2nd number = column


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# linspace will return evenly spaced numbers over a specified interval
# linspace is different than range function
# its third argument is not a step size, it will shows num of points we want

In [24]:
np.linspace(0,5,10)
# it will give us 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.linspace(0,5,100)
# one dimesnional since array([]) has one bracket

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [31]:
#. The spacing between the points is (x2-x1)/(n-1).

np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [32]:
# identity matrix
# all diagonals have 0'2
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.random.rand(5) # press tab after dot to see all the functions

# getting random number for 1 dimenstional
# uniform distribution

array([0.31797244, 0.32130946, 0.61653144, 0.44231895, 0.13789838])

In [35]:
np.random.rand(5,5)

# random 2 dimensional vector with 5 rows and 5 column
# uniform distribution

array([[0.32263281, 0.62870362, 0.70370293, 0.32138231, 0.69255538],
       [0.84145866, 0.74942859, 0.5645608 , 0.20301706, 0.38063918],
       [0.35590892, 0.31584886, 0.83616322, 0.10707226, 0.48582706],
       [0.01373623, 0.53125122, 0.81909373, 0.82771201, 0.08767393],
       [0.72596529, 0.94084273, 0.70028028, 0.96051971, 0.46548715]])

In [37]:
np.random.randn(2)

# different than the random.rand
# it doesn't give us the uniform distribution
# it gives us the 2 random points from standard normal distribution

array([-0.76211107,  0.00848855])

In [38]:
np.random.randn(4,4)

array([[-0.09292326,  0.59178099,  1.00134904,  0.45443971],
       [-0.37511372,  0.6128079 ,  0.19375961,  0.58046806],
       [ 0.04689449, -0.07828654, -0.62916185,  0.74883852],
       [-0.34944207,  0.12091341, -1.08983898,  0.19897495]])

In [39]:
np.random.randint(1,100) # 1-99


24

In [40]:
arr = np.arange(25)
arr

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr

array([27, 10,  0, 40, 39, 25,  3, 23, 21, 17])

In [48]:
# useful method to use with an array
# reshape method
# that will return the new shaped array

arr.reshape(5,5)

# one thing to note we cannot put a combination of rows that have a product of 
# greater than the number of items in original arr
# in the original arr we have total 25so the product of 
# arr.reshape(row,col) should be 25 ie. (5,5) or (25,1) or (1,25)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
arr.reshape (5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [51]:
arr.reshape (25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [53]:
ranarr.max()

40

In [54]:
ranarr.min()

0

In [60]:
ranarr.argmax() # get the position of maximum item in an array

3

In [61]:
ranarr.argmin() # get the position of minimum item in an array

2

In [62]:
arr # one dimensional

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr.shape # to see the shape of our matrix

(25,)

In [65]:
arr.dtype # finding data type

dtype('int32')

# Numpy Indexing and selection

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [71]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [73]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [74]:
arr[0:5] = 100 #will change all the first 5 digits to 100

In [75]:
arr = np.arange(0,11)

In [76]:
slice_of_arr = arr[0:6] #slicing

In [77]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [78]:
slice_of_arr[:] #further slicing on the created slicing variable

array([0, 1, 2, 3, 4, 5])

In [79]:
slice_of_arr[:] = 99 # chaning all the elements to 99

In [81]:
arr # note that once we call back the original array
    # the effect of slice_of_arr also chnaged the first 5 elements of arr
    # array, this is because numpy doesn't create copies on it's own
    # to save the memory and avoid complex issues
    # however we can make a copy of our own

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
arr_copy = arr.copy ()

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
arr_copy[:] = 100

In [87]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [88]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D ARRAY

In [90]:
arr_2d = np.array([[5,10,15], [20,25,30], [30,40,45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [93]:
#two methods for grabbing elements from 2dimensional array


arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [94]:
arr_2d[0][0] # 0 row and 0 column

5

In [95]:
arr_2d[0] # select row 0

array([ 5, 10, 15])

In [96]:
arr_2d[1][1]

25

In [97]:
arr_2d[2][1]

40

In [98]:
arr_2d[1][2]

30

In [ ]:
# second method --- comma single bracket notation

In [99]:
arr_2d[1,2]

30

In [101]:
arr_2d[2,1]

40

In [103]:
# grabing entire section of an array rather a number

In [104]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [105]:
arr_2d[:2,1:] # get row 0 and 1 and col 1 and 2



array([[10, 15],
       [25, 30]])

In [106]:
arr_2d[:2] # just selects th rows regradless of column
            # rows 0 and 1
            #and all columns since we didn't specify columns

array([[ 5, 10, 15],
       [20, 25, 30]])

In [107]:
arr = np.arange(1,11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
# getting boolean out of an array wey comparing with a value

bool_arr = arr > 5

In [113]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [115]:
arr[bool_arr] # getting the values back which had a 
             #  boolean value = True
              

array([ 6,  7,  8,  9, 10])

In [118]:
arr[arr > 5] # shorter version of the above 2 line steps
             # instead of creating boolean first we can directly
            # do it in this manner

array([ 6,  7,  8,  9, 10])

In [119]:
# all elements of array that are less than 3

arr[arr < 3 ]

array([1, 2])

In [127]:
arr_2d2 = np.arange(50).reshape(5,10)

In [128]:
arr_2d2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [131]:
#grabbing 13,14,23,24

arr_2d2[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [132]:
arr_2d[1:3] # all rows from 1 till 2

array([[20, 25, 30],
       [30, 40, 45]])

# Numpy Operations 

In [133]:
import numpy as np

In [134]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [138]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [142]:
arr + 100 # integet will be added to every element of the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [143]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [144]:
arr / arr
# warning will be given when /0 or when 1/0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [145]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [146]:
# universal arry function


#square root of every element in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [147]:
# exponential of every element
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [148]:
arr.max()

10

In [150]:
np.log(arr) # warning due to zero division or infinity

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])